#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           frontRight,    tmotorServoContinuousRotation, openLoop, reversed)//front right motor
#pragma config(Motor,  port2,           backRight,    tmotorServoContinuousRotation, openLoop, reversed)//back right motor
#pragma config(Motor,  port3,           frontLeft,     tmotorServoContinuousRotation, openLoop)//front left motor
#pragma config(Motor,  port4,           backLeft,        tmotorServoContinousRotation,  openLoop)//back left motor
#pragma config(Motor,  port6,           claw,          tmotorServContinousRotation,   openLoop)
#pragma config(Motor,  port8,           lift1,         tmotorServoContinousRotation, openLoop)
#pragma config(Motor,  port9,           lift2,         tmotorServoContinousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard
//	This setup is for the SQUAREBOT	model

/************************************\
|*  Robot Virtual World Template    *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

void stop(){
	motor[frontRight] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[backLeft]= 0;
}


void forward(int speed, int time) {
	motor[frontLeft] = speed;
	motor[backLeft] = speed;
	motor[frontRight] = speed;
	motor[backRight] = speed;
	wait1Msec(time);
stop();
}//end of function

void lift(int speed, int time) {
   motor[lift1] = speed;
   motor[lift2] = speed;
   wait1Msec(time);
}

void grab(int speed, int time) {
	motor[claw] = speed;
	wait1Msec(time);

}

void turnRight(int speed, int time) {
	motor[frontLeft] = -speed;
	motor[backLeft] = -speed;
	motor[frontRight] = speed;
	motor[backRight] = speed;
	wait1Msec(time);

}

void turnLeft(int speed, int time) {
	motor[frontLeft] = speed;
	motor[backLeft] = speed;
	motor[frontRight] = -speed;
	motor[backRight] = -speed;
	wait1Msec(time);
}



task main()
{
	turnRight(65, 1500);
	forward(75, 2800);//go forward
	lift(90, 6000);
	turnRight(65, 400);
	forward(75, 500);



}
