#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           right1,        tmotorServoContinousRotation,  openLoop, reversed)
#pragma config(Motor,  port5,           left1,         tmotorServoContinousRotation,  openLoop)
#pragma config(Motor,  port8,           lift1,         tmotorServoContinousRotation, openLoop)
#pragma config(Motor,  port9,           lift2,         tmotorServoContinousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard
//	This setup is for the SQUAREBOT	model

/************************************\
|*  Robot Virtual World Template    *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

void forward() {

while(true) {
  // your code goes here
	motor[rightMotor] = 75;
	motor[leftMotor] = -75;
	motor[right1] = 75;
	motor[left1] = -75;
	wait1Msec(1000);
	motor[rightMotor] = 0;
	motor[right1] = 0;
	motor[left1] = 0;
	motor[leftMotor]= 0;

}//i love

}//end of function

void lift() {
   motor[lift1] = 80;
   motor[lift2] = 80;

}



task main()
{

	// your code goes here
	forward();
	lift();

}
